resources:
- https://github.com/redhat-appstudio/dora-metrics/deploy/base?ref=db06bc11b8178e01ce55447e44e1aeed9784d44f

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/redhat-appstudio/dora-metrics
    newName: quay.io/redhat-appstudio/dora-metrics
    newTag: db06bc11b8178e01ce55447e44e1aeed9784d44f
